version: "3"
services:
  web:
    image: reincarnation
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    links:
      - mongo
    ports:
      - "4001:2777"
    networks:
      - webnet
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27777:27777"
networks:
  webnet: